title: Sebastian Palacio Betancur
logo: images/me.png
description: Control Engineering | Robotics | AI | Data Science
# show_downloads: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
